[package]
name = "qfetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
eyre = "0.6.9"
log = "0.4.20"
owo-colors = "3.5.0"
pretty_env_logger = "0.5.0"
sysinfo = "0.29.11"
